sass:
    sass_dir: _sass
cloudcannon:
  data: true
collections:
  yoga:
    output: true
  retreats:
    output: true
faqs: []
_array_structures:
  faqs:
    - label: Inclusions
      icon: text
      value:
        _id: inclusions
        inclusions_description_html:
    - label: Exclusions
      icon: text
      value:
        _id: exclusions
        exclusions_description_html:
    - label: Accommodation
      icon: text
      value:
        _id: accommodation
        accommodation_description_html:
    - label: What to bring
      icon: text
      value:
        _id: what-to-bring
        what-to-bring_description_html:
    - label: Special requests
      icon: text
      value:
        _id: special-requests
        special-requests_description_html:
    - label: Weather
      icon: text
      value:
        _id: weather
        weather_description_html:
