sass:
    sass_dir: _sass
cloudcannon:
  data: true
collections:
  yoga:
    output: true
  retreats:
    output: true
  offerings:
    output: true
defaults:
  -
    scope:
      path: ""
    values:
      _options:
        banner_image:
          # 16:9 aspect ratio for banner
          width: 2000
          height: 1125

faqs: []
_array_structures:
  faqs:
    - label: FAQ
      icon: text
      description: Add or edit Frequently Asked Question
      value:
        _id: faq
        faq-title:
        faq_description_html:

uploads_dir: "/assets/images/:title"
markdown: kramdown
<<<<<<< HEAD

# removes the date from the permalink
permalink: '/:title'

=======
>>>>>>> parent of e0b33da... Set up Markdown syntax for posts
plugins:
  - jekyll-archives
jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
