url: 'https://claudianeumann.yoga'
sass:
    sass_dir: _sass
    style: compressed
cloudcannon:
  data: true
collections:
  yoga:
    output: true
  retreats:
    output: true
  offerings:
    output: true
  posts:
    output: true
    permalink: "/yogismile/:year/:title"
defaults:
  -
    scope:
      path: ""
    values:
      _options:
        banner_image:
          # 16:9 aspect ratio for banner
          width: 2000
          height: 1125
        feature-box-1_image:
          width: 600
        feature-box-2_image:
          width: 600
        feature-box-3_image:
          width: 600
        feature-retreat_image:
          width: 800

faqs: []
_array_structures:
  faqs:
    - label: FAQ
      icon: text
      description: Add or edit Frequently Asked Question
      value:
        _id: faq
        faq-title:
        faq_description_html:

uploads_dir: "/assets/images/:title"
markdown: kramdown

# removes the date from the permalink
# permalink: '/:title/'

# Plugins & Configurations
plugins:
  - jekyll-archives
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-srcset
  - jekyll-responsive-image

responsive_image:
  template: _includes/responsive-image.html #THIS ONE
  default_quality: 90
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
      quality: 90
  base_path: assets/images/
  output_path_format: assets/images/srcset/%{width}/%{basename}


jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/yogismile/tag/:name/'
    category: '/yogismile/category/:name/'
