sass:
    sass_dir: _sass

cloudcannon:
  data: true

collections:
  yoga:
    output: true
  retreats:
    output: true
  offerings:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      _options:
        banner_image:
          # 16:9 aspect ratio for banner
          width: 2000
          height: 1125

faqs: []
_array_structures:
  faqs:
    - label: FAQ
      icon: text
      description: Add or edit Frequently Asked Question
      value:
        _id: faq
        faq-title:
        faq_description_html:

# sets the upload directory for images
uploads_dir: "/assets/images/:title"

markdown: kramdown

# removes the date from the permalink
permalink: '/:title'

plugins:
  - jekyll-archives

jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
