sass:
    sass_dir: _sass
cloudcannon:
  data: true
collections:
  yoga:
    output: true
  retreats:
    output: true
  offerings:
    output: true
faqs: []
_array_structures:
  faqs:
    - label: FAQ
      icon: text
      description: Add or edit Frequently Asked Question
      value:
        _id: faq
        faq-title:
        faq_description_html:
