url: 'https://claudianeumann.yoga'
sass:
    sass_dir: _sass
    style: compressed
cloudcannon:
  data: true
collections:
  yoga:
    output: true
  retreats:
    output: true
  offerings:
    output: true
  posts:
    output: true
    permalink: "/yogismile/:year/:title"
defaults:
  -
    scope:
      path: ""
    values:
      _options:
        banner_image:
          # 16:9 aspect ratio for banner
          width: 2000
          height: 1125
        feature-box-1_image:
          width: 600
        feature-box-2_image:
          width: 600
        feature-box-3_image:
          width: 600
        feature-retreat_image:
          width: 800
  -
    scope:
      path: "/posts" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "blog"
      title:
      author: Claudia
      banner_image:
      categories: []
      tags: []
      keywords: []
      description: This is a very important section for SEO as it is the part where the Google search crawlers scan when indexing pages; make it descriptive of the page content thinking it's the first thing people will read when searching online        
  -
    scope:
      path: "/retreats"
    values:
      layout: retreat
      _hidden_info-box: retreat
      display:
      page_title:
      banner_heading:
      banner_image:
      banner_image-alt-text:
      add_banner_button: true
      banner-cta-button_url:
      banner-cta-button_text:
      box-1_image:
      retreat-date:
      retreat-location:
      retreat-price:
      retreat-recommended-for_html:
      faqs:
      location-highlights-background_image:
      location-highlights-background-image-alt-text:
      location-description_html:
      highlight-1:
      highlight-2:
      highlight-3:
  -
    scope:
      path: "/yoga"
    values:
      layout: "yoga"
      _hidden_info-box: yoga
      page_title:
      banner_heading:
      banner_image:
      banner_image-alt-text:
      class-duration:
      class-flow-type_html:
      class-recommended-for_html:
      class-prices:
      show_private_section: false
      box-1_image:
      add_testimonials: true
      testimonials:
        - content:
          reviewer:
      add_schedule: true
      schedule:
        - day:
          classes:
            - time-bracket:
              style:
              studio:
              studio_url:
              add-to-cal:
        - day:
          classes:
            - time-bracket:
              style:
              studio:
              studio_url:
              add-to-cal:
  
    
_comments:
  event-location_url: Place the map link here
  event-map_embed_code_block: Place the Google Maps Embed code here
faqs: []
_array_structures:
  faqs:
    - label: FAQ
      icon: text
      description: Add or edit Frequently Asked Question
      value:
        _id: faq
        faq-title:
        faq_description_html:

uploads_dir: "/assets/images/:title"
markdown: kramdown

# removes the date from the permalink
# permalink: '/:title/'

# Plugins & Configurations
plugins:
  - jekyll-archives
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-srcset
  - jekyll-responsive-image

responsive_image:
  template: _includes/responsive-image.html #THIS ONE
  default_quality: 90
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
      quality: 90
  base_path: assets/images/
  output_path_format: assets/images/srcset/%{width}/%{basename}

jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/yogismile/tag/:name/'
    category: '/yogismile/category/:name/'
  
  
