blog_settings:
  blog-owner: Claudia Neumann
  profile-picture_image: /assets/images/placeholder 010.jpg

colors:
  # HEX codes have to be wrapped by SINGLE QUOTES to respect YAML syntax
  primary_color: '#479AA1'
  secondary_color: '#F5AEA8'
  accent_color: '#D9D9D9'
  dark_color: '#707070'
  light_color: '#f1f1f1'

fonts:
  # font family must add DOUBLE QUOTES to respect YAML syntax
  header_font_family: "'Megrim', cursive;"
  heading1-font-size: 3rem
  heading2-font-size: 2rem
  heading3-font-size: 2rem
  # code blocks must be put between SINGLE QUOTE marks to respect YAML syntax
  heading_font_code_block: '<link href="https://fonts.googleapis.com/css?family=Megrim&display=swap" rel="stylesheet">'
  paragraph_font_family: "'Gotu', sans-serif;"
  paragraph-font-size: 1rem
  paragraph-line-height: 1.7
  paragraph_font_code_block: '<link href="https://fonts.googleapis.com/css?family=Gotu&display=swap" rel="stylesheet">'
  light_font: 200
  regular_font: 400
  bold_font: 600
  extra_bold_font: 700

buttons:
  button-border-radius: 5px
  cta-button-font-size: 1rem
  learn-more-button-font-size: .7rem
