basic_settings:
  site_logo: assets/images/yogismile-logo.png

colors:
  # HEX codes have to be wrapped by SINGLE QUOTES to respect YAML syntax
  primary_color: '#479AA1'
  secondary_color: '#F5AEA8'
  accent_color: '#D9D9D9'
  dark_color: '#707070'
  light_color: '#FFF'

fonts:
  # font family must add DOUBLE QUOTES to respect YAML syntax
  header_font_family: "'Raleway', sans-serif;"
  heading1-font-size: 3rem
  heading2-font-size: 2rem
  heading3-font-size: 2rem
  # code blocks must be put between SINGLE QUOTE marks to respect YAML syntax
  heading_font_code_block: '<link href="https://fonts.googleapis.com/css?family=Raleway:200,400,600,700&display=swap" rel="stylesheet">'
  paragraph_font_family: "'Nunito', sans-serif;"
  paragraph-font-size: 1.2rem
  paragraph-line-height: 1.7
  paragraph_font_code_block: '<link href="https://fonts.googleapis.com/css?family=Nunito:300,400,600&display=swap" rel="stylesheet">'
  light_font: 200
  regular_font: 400
  bold_font: 600
  extra_bold_font: 700

buttons:
  button-border-radius: 5px
  cta-button-font-size: 1rem
  learnmore-button-font-size: .7rem

calendars:
  calendly_url: 'https://www.calendly.com'

social:
  facebook_url: 'https://facebook.com'
  instagram_url: 'https://instagram.com'
  youtube_url: 'https://youtube.com'

yoga-styles:
  - Vinyasa
  - Corporate
  - Yin
  - Hatha
  - Meditation

studios:
  - Studio 1
  - Studio 2
  - Studio 3

nav-menu:
  menu-1-name: About
  menu-2-name: Yoga
  menu-3-name: Heal
  menu-4-name: Grow
  menu-5-name: Health
  menu-6-name: Contact
