colors:
  # HEX codes have to be wrapped by SINGLE QUOTES to respect YAML syntax
  primary_color: '#479AA1'
  secondary_color: '#F5AEA8'
  accent_color: '#D9D9D9'
  dark_color: '#707070'
  light_color: '#FFF'

fonts:
  # font family must add DOUBLE QUOTES to respect YAML syntax
  header_font_family: "'Raleway', sans-serif;"
  # code blocks must be put between SINGLE QUOTE marks to respect YAML syntax
  heading_font_code_block: '<link href="https://fonts.googleapis.com/css?family=Raleway:200,400,600,700&display=swap" rel="stylesheet">'
  paragraph_font_family: "'Nunito', sans-serif;"
  paragraph_font_code_block: '<link href="https://fonts.googleapis.com/css?family=Nunito:300,400,600&display=swap" rel="stylesheet">'
  light_font: 200
  regular_font: 400
  bold_font: 600
  extra_bold_font: 700

buttons:
  button-font-size: 1rem
  button-border-radius: 5px
