basic_settings:
  site_name: Claudia Neumann Yoga
  site_logo_image: /assets/images/yogismile-logo.png
  contact-email: happy@claudianeumann.yoga
images:
  community_image: /assets/images/srcset/2000/claudia-neumann-yoga-124.jpg
  private-section_image: /assets/images/srcset/2000/claudia-neumann-yoga-154.jpg
colors:
  primary_color: '#479aa1'
  accent_color: '#f5aea8'
  dark_color: '#707070'
  light_color: '#f1f1f1'
fonts:
  header_font_family: "'Megrim', cursive;"
  heading1-font-size: 3rem
  heading2-font-size: 2rem
  heading3-font-size: 2rem
  heading_font_code_block: >-
    <link href="https://fonts.googleapis.com/css?family=Megrim&display=swap" rel="stylesheet">
  paragraph_font_family: "'Gotu', sans-serif;"
  paragraph-font-size: 1rem
  paragraph-line-height: 1.7
  paragraph_font_code_block: >-
    <link href="https://fonts.googleapis.com/css?family=Gotu&display=swap" rel="stylesheet">
  light_font: 200
  regular_font: 400
  bold_font: 600
  extra_bold_font: 700
forms:
  formspree_url: 'https://formspree.io'
buttons:
  button-border-radius: 5px
  cta-button-font-size: 1rem
  learn-more-button-font-size: .7rem
calendars:
  calendly_url: 'https://calendly.com/claudianeumannyoga'
  reiki_calendly_url: 'https://calendly.com/claudianeumannyoga/1hr-reiki-session'
  yoga_calendly_url: 'https://calendly.com/claudianeumannyoga/1-30hr-private-yoga-class'
social:
  facebook_url: 'https://facebook.com'
  instagram_url: 'https://instagram.com'
  youtube_url: 'https://youtube.com'
nav-menu:
  menu-1-name: About
  menu-1-link_url: /about
  menu-2-name: Yoga
  menu-2-link_url: /yoga
  menu-3-name: Heal
  menu-3-link_url: /offerings/reiki
  menu-4-name: Grow
  menu-4-link_url: /retreats
  menu-5-name: Health
  menu-5-link_url: /yogismile/
  menu-6-name: Contact
  menu-6-link_url: 'mailto:happy@claudianeumann.yoga'
blog-settings:
  blog-owner: Claudia Neumann
  profile-picture_image: /assets/images/srcset/600/claudia-neumann-yoga-101.jpg
  ad_image: https://via.placeholder.com/300x400
  colors:
    # HEX codes have to be wrapped by SINGLE QUOTES to respect YAML syntax
    primary_color: '#479AA1'
    secondary_color: '#F5AEA8'
    accent_color: '#D9D9D9'
    dark_color: '#707070'
    light_color: '#f1f1f1'
  fonts:
    # font family must add DOUBLE QUOTES to respect YAML syntax
    header_font_family: "'Megrim', cursive;"
    heading1-font-size: 3rem
    heading2-font-size: 2rem
    heading3-font-size: 2rem
    # code blocks must be put between SINGLE QUOTE marks to respect YAML syntax
    heading_font_code_block: '<link href="https://fonts.googleapis.com/css?family=Megrim&display=swap" rel="stylesheet">'
    paragraph_font_family: "'Gotu', sans-serif;"
    paragraph-font-size: 1rem
    paragraph-line-height: 1.7
    paragraph_font_code_block: '<link href="https://fonts.googleapis.com/css?family=Gotu&display=swap" rel="stylesheet">'
    light_font: 200
    regular_font: 400
    bold_font: 600
    extra_bold_font: 700
  buttons:
    button-border-radius: 5px
    cta-button-font-size: 1rem
    learn-more-button-font-size: .7rem
